version: "3.8"

services:
  next-app:
    image: ghcr.io/crisp-sh/landing:latest
    networks:
      - proxy
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://crisp.sh
      - EMAILOCTOPUS_API_KEY=${EMAILOCTOPUS_API_KEY}
      - LIST_ID=${LIST_ID}
    deploy:
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.next-app.rule=Host(`crisp.sh`)"
        - "traefik.http.routers.next-app.entrypoints=websecure"
        - "traefik.http.routers.next-app.tls=true"
        - "traefik.http.routers.next-app.tls.certresolver=cloudflare"
        - "traefik.http.services.next-app.loadbalancer.server.port=3000"
        - "traefik.swarm.network=proxy"
        - "com.crispsh.autodeploy=true"

networks:
  proxy:
    external: true
