name: Docker Build and Publish

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has packages:write permission

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Set context to the repository root, where package.json etc. are located
          context: . 
          # Keep file path relative to the root context
          file: ./app/prod.Dockerfile 
          push: true
          tags: ghcr.io/crisp-sh/landing:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Pass secrets as build arguments
          # IMPORTANT: Create these secrets in your GitHub repo settings!
          build-args: |
            ENV_VARIABLE=${{ secrets.ENV_VARIABLE }}
            NEXT_PUBLIC_ENV_VARIABLE=${{ secrets.NEXT_PUBLIC_ENV_VARIABLE }} 